export default [
  { text: '主页', link: 'https://hog-starwatch.github.io/', target: '_self', },
  { text: '背景资料',
    items: [
      { text: '关于SCP基金会', link: '/背景资料/关于SCP基金会.md' },
      { text: '相关组织', link: '/背景资料/相关组织.md' },
      { text: '项目等級', link: '/背景资料/项目等級.md' },
      { text: '安保许可等级', link: '/背景资料/安保许可等级.md' },
      { text: '安保设施', link: '/背景资料/安保设施.md' },
      { text: '机动特遣队', link: '/背景资料/机动特遣队.md' },
      { text: '中国相关组织', link: '/背景资料/中国相关组织.md' },
      { text: '中国分部设施', link: '/背景资料/安保设施地点-CN.md' },
      { text: '中国分部机动特遣队', link: '/背景资料/机动特遣队-CN.md' },
      { text: '基金会术语汇编', link: '/背景资料/基金会术语汇编.md' },
    ],
  },
  { text: 'SCP系列',
    items: [
      { text: 'SCP系列-Wikidot原网址', link: 'https://scp-wiki-cn.wikidot.com/scp-series' },
      { text: 'SCP系列-I(001-999)', link: '/SCP系列/SCP系列-I.md' },
      { text: 'SCP系列-I-故事', link: '/SCP系列/SCP系列-I-故事.md' },
      { text: 'SCP系列-II(1000-1999)', link: '/SCP系列/SCP系列-II.md' },
      { text: 'SCP系列-II-故事', link: '/SCP系列/SCP系列-II-故事.md' },
      { text: 'SCP系列-III(2000-2999)', link: '/SCP系列/SCP系列-III.md' },
      { text: 'SCP系列-III-故事', link: '/SCP系列/SCP系列-III-故事.md' },
      { text: 'SCP系列-IV(3000-3999)', link: '/SCP系列/SCP系列-IV.md' },
      { text: 'SCP系列-IV-故事', link: '/SCP系列/SCP系列-IV-故事.md' },
      { text: 'SCP系列-V(4000-4999)', link: '/SCP系列/SCP系列-V.md' },
      { text: 'SCP系列-V-故事', link: '/SCP系列/SCP系列-V-故事.md' },
      { text: 'SCP系列-VI(5000-5999)', link: '/SCP系列/SCP系列-VI.md' },
      { text: 'SCP系列-VI-故事', link: '/SCP系列/SCP系列-VI-故事.md' },
      { text: 'SCP系列-VII(6000-6999)', link: '/SCP系列/SCP系列-VII.md' },
      { text: 'SCP系列-VII-故事', link: '/SCP系列/SCP系列-VII-故事.md' },
      { text: 'SCP系列-VIII(7000-7999)', link: '/SCP系列/SCP系列-VIII.md' },
      { text: 'SCP系列-VIII-故事', link: '/SCP系列/SCP系列-VIII-故事.md' },
      { text: 'SCP系列-IX(8000-8999)', link: '/SCP系列/SCP系列-IX.md' },
      { text: '搞笑SCP', link: '/SCP系列/搞笑SCP.md' },
      { text: '搞笑SCP-故事', link: '/SCP系列/搞笑SCP-故事.md' },
      { text: '已解明SCP', link: '/SCP系列/已解明SCP.md' },
      { text: '已解明SCP-故事', link: '/SCP系列/已解明SCP-故事.md' },
    ],
  },
];